import { User } from "./types/User";

export class TAG_QuestionText {
  public Title: string;
  public ServiceLine: string;
  public Q1: string;
  public Q2: string;
  public Q3: string;
  public Q4: string;
  public Q5: string;
  public Q6: string;
  public Q7: string;
  public Q8: string;
  public Q9: string;
  public Q10: string;
  public Q11: string;
  public Q12: string;
  public Q13: string;
  public Q14: string;
  public Q15: string;
  public Q16: string;
  public Q17: string;
  public Q18: string;

  public Q1Category: string;
  public Q2Category: string;
  public Q3Category: string;
  public Q4Category: string;
  public Q5Category: string;
  public Q6Category: string;
  public Q7Category: string;
  public Q8Category: string;
  public Q9Category: string;
  public Q10Category: string;
  public Q11Category: string;
  public Q12Category: string;
  public Q13Category: string;
  public Q14Category: string;
  public Q15Category: string;
  public Q16Category: string;
  public Q17Category: string;
  public Q18Category: string;

  public Q1IsRating?: boolean;
  public Q2IsRating?: boolean;
  public Q3IsRating?: boolean;
  public Q4IsRating?: boolean;
  public Q5IsRating?: boolean;
  public Q6IsRating?: boolean;
  public Q7IsRating?: boolean;
  public Q8IsRating?: boolean;
  public Q9IsRating?: boolean;
  public Q10IsRating?: boolean;
  public Q11IsRating?: boolean;
  public Q12IsRating?: boolean;
  public Q13IsRating?: boolean;
  public Q14IsRating?: boolean;
  public Q15IsRating?: boolean;
  public Q16IsRating?: boolean;
  public Q17IsRating?: boolean;
  public Q18IsRating?: boolean;
}
